server:
  port: 9201

spring:
  application:
    name: file-client

eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
  instance:
    hostname: localhost

hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false #禁用熔断器超时时间
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断器超时时间。解决第一次调用失败问题。

zsw:
  base:
    serverName:
      file: file-api
    config:
      file:
        max-file-size: 10mb
        max-request-size: 10mb
        mapProps:
          test: 1