##服务器端口
server:
  port: 10001

##微服务名
spring:
#  boot:
#    admin:
#      url: http://localhost:9104/
#      username: user
#      password: user
  application:
    name: api-server
    admin:
      enabled: true
##服务发现地址
eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
    disable-delta: true
  instance:
    hostname: localhost
    prefer-ip-address: true

endpoints:
  # 大部分 actuator 需要 ACTUATOR 才能访问 这里脱敏 普通 security 可访问
  sensitive: false
  health:
    sensitive: false
    enabled: true
  shutdown:
    enabled: true
    sensitive: false
  logfile:
    enabled: true
    external-file: ${logging.file}



info:
  version: @project.version@
logging:
  config: classpath:logback-spring.xml
  path: /data/spring/logs
