server:
  port: 8088
spring:
  application:
    name: this-is-a-test
management:
  endpoints:
    web:
      exposure:
        include: "*"
    # 开启 micrometer 以 prometheus 输出，然后脱敏
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true


