server:
  port: 8080
spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 50
        queue-capacity: 500
    scheduling:
      pool:
        size: 4
  redis:
    host: localhost
    port: 6379
#    password: Anf34l_Fs
#    database: 5
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
logging:
  level:
    com.zsw: DEBUG
#    timeout: 60