version: '3'
services:
#  redis:
#    container_name: redis
#    image: redis
#    ports:
#      - 6379:6379

  eureka:
    container_name: eureka
    build: ./
    image: zsw/register-server
    restart: 'no'
    networks:
      - backend
    ports:
      - 1111:1111
    env_file:
      - eureka.env



networks:
  backend:
    driver: bridge
    external: true

# 详情见 https://docs.docker.com/compose/compose-file/