server:
  port: 80


spring:
  jpa:
    database: mysql
    show-sql: true
#    generate-ddl: true
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    #    cluster: 集群
    #      nodes:
    #        - 192.168.0.17:6390
    #        - 192.168.0.17:6391
    #        - 192.168.0.17:6392
    #        - 192.168.0.9:6390
    #        - 192.168.0.9:6391
    #        - 192.168.0.9:6392
      ##Redis服务器地址---如果没有配置 默认 127.0.0.1:6379 无密码
    host:
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      ## 连接池中的最大空闲连接
      max-idle: 8
      ## 连接池中的最小空闲连接
      min-idle: 1
    ## 连接超时时间（毫秒）
    timeout: 0

  ##必要，RedisCacheManager 存储索引
  ##spring.cache.cache-names=users
  ##自定义RedisCacheManger配置
  ## 名称 -- 缓存有效期：s -------不同缓存分类后制定不同的有效期
zsw:
  base:
    redis:
      configuration:
        expires:
          list: 1800
          proxy: 900
          users: 1800