server:
  port: 80

spring:
  application:
    name: zipkin-server
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/zipkin?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

zipkin:
  storage:
    type: mysql

##服务发现地址
eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
  instance:
    hostname: localhost

#es存储
#zipkin:
#  storage:
#    type: elasticsearch
#    elasticsearch:
#      cluster: ${ES_CLUSTER:elasticsearch}
#      hosts: ${ES_HOSTS:localhost:9300}
#      index: ${ES_INDEX:zipkin}
#      index-shards: ${ES_INDEX_SHARDS:5}
#      index-replicas: ${ES_INDEX_REPLICAS:1}


logging:
  level: debug
