version: '3'
services:
#  redis:
#    container_name: redis
#    image: redis
#    ports:
#      - 6379:6379

  eureka:
    container_name: eureka
    build: ./server/register-server
#    image: zsw/register-server
    restart: 'no'
    ports:
      - 1111:1111

  api-server:
    container_name: api-server
    build: ./server/api-server
#    image: zsw/api-server
    restart: always
    ports:
      - 3334:3334
    extra_hosts:
      - redis:192.168.56.1
    depends_on:
      - eureka
#      - redis
    links:
      - eureka
#      - redis


# 详情见 https://docs.docker.com/compose/compose-file/