#服务器端口
server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:oauth2.jks
#    key-password: 111111
#    key-alias: oauth2

com:
  zsw:
    resource:
      resource-id: 2a1b448f53f7b4ee1bc5
      verifier-key-file: /data/keystore/publicKey.key

#logging:
#  level: debug
logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3

info:
  version: @project.version@
#debug: true