spring:
  application:
    name: wechat-server
server:
  port: 80
wechat:
  mp:
    app-id: wx99a5a3383c6f0bb2
    secret: 590ab159862fd0f2167131b507e4f32a
    token: fo4CexQa4OBgvmcFRp4pAydnNtmwtZbV
    oauth2redirect-uri: http://3109faaf.nat123.cc/oauth2/code
#    aes-key:



