spring:
  application:
    name: wechat-server
  # 使用mq bus刷新
#  rabbitmq:
#    username: guest
#    password: guest
#    addresses: localhost
#    port: 5672
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      profile: test
      failFast: true
      name: file
server:
  port: 80

eureka:
  server:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone:  http://${eureka.server.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  security:
    enabled: false
wechat:
  mp:
    app-id: ****
    secret: ****
    token: ****
    oauth2redirect-uri: ****
#    aes-key:



