##服务器端口
server:
  port: 3335
  tomcat:
    port-header: PUT,DELETE,OPTIONS,GET,POST
    # 最大连接数
    max-connections: 0
    # 连接数满后 等待 queue 长度
    accept-count: 0
    # 应用内最大线程数
    max-threads: 0



##微服务名
spring:

  application:
    name: ui-server
  output:
    ansi:
      enabled: detect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 5MB
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  freemarker:
    suffix: .html


management:
  security:
    enabled: false

info:
  version: @project.version@







