server:
  port: 3333

spring:
  application:
    name: file-api

eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.conf.eureka-server-port}/eureka/
    eureka-server-port: 1111
  instance:
    hostname: localhost
