server:
  port: 13333

spring:
  application:
    name: file-core

eureka:
  server:
    hostname: 192.168.1.12
  client:
    serviceUrl:
      defaultZone:  http://${eureka.server.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 17101
  instance:
    prefer-ip-address: true
#    hostname: 192.168.1.12

