server:
  port: 80
#ƒ¨»œ π”√≈‰÷√
spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.zsw.persistence.entity
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
