server:
  port: 18080


spring:
  application:
    name: bussiness-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.12:3306/st_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      #      max-lifetime: 30000
      idle-timeout: 600000
      connection-timeout: 30000
      register-mbeans: true

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  client:
    rm:
      report-success-enable: true
      report-retry-count: 5
      table-meta-check-enable: false
      async-commit-buffer-limit: 10000
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
    log:
      exception-rate: 100





eureka:
  client:
    serviceUrl:
      defaultZone:  http://192.168.1.12:7101/eureka/
logging:
  level:
    io.seata: DEBUG
