##服务器端口
server:
  port: 8080


spring:
  freemarker:
    suffix: .html
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
  jackson:
    serialization:
      failOnEmptyBeans: false
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: oauth2-client
  redis:
    #    cluster: 集群
    #      nodes:
    #        - 192.168.0.17:6390
    #        - 192.168.0.17:6391
    #        - 192.168.0.17:6392
    #        - 192.168.0.9:6390
    #        - 192.168.0.9:6391
    #        - 192.168.0.9:6392
      ##Redis服务器地址---如果没有配置 默认 127.0.0.1:6379 无密码
    host: localhost
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: 111111
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      ## 连接池中的最大空闲连接
      max-idle: 8
      ## 连接池中的最小空闲连接
      min-idle: 1
    ## 连接超时时间（毫秒）
    timeout: 0




zsw:
  base:
    redis:
      configuration:
        expires:
          list: 1800
          proxy: 900
          users: 1800
          customers: 1800

logging:
  file: /data/spring/${spring.application.name}.log
  level:
    org.springframework.security: DEBUG
security:
  oauth2:
    resource:
      filter-order: 3