security:
  oauth2:
    client:
      client-id: 2a1b448f53f7b4ee1bc5
      client-secret: 9ac0814f8f098395033d99031620c13d6279bad8
      access-token-uri: http://oauth2-server/oauth/token
      user-authorization-uri: http://oauth2-server/oauth/authorize
      pre-established-redirect-uri: http://localhost:1301/callback
