server:
  port: 9201

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: file-conf
  servlet:
    multipart:
#      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  http:
    encoding:
      charset: UTF-8




eureka:
  server:
    hostname: 192.168.1.12
  client:
    serviceUrl:
      defaultZone:  http://${eureka.server.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 17101
  instance:
    prefer-ip-address: true
#    hostname: 192.168.1.12


zsw:
  client:
    servername:
      file: file-core