server:
  port: 80


security:
  user:
    password: 111111
  ignored: /
  sessions: never
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: 2a1b448f53f7b4ee1bc5
      client-secret: 9ac0814f8f098395033d99031620c13d6279bad8
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false