spring:
#  profiles:
#    active: aliyun
  application:
    name: rocketmq


--- # aliyun mq
spring:
  profiles:
rocketmq:
  name-server:
  producer:
    group:
    sendMessageTimeout: 300000
    access-key:
    secret-key:
  consumer:
    access-key:
    secret-key:
--- # local rocketmq
spring:
  profiles: default
rocketmq:
  name-server:
  producer:
    group:
    sendMessageTimeout:
    access-key:
    secret-key:
  consumer:
    access-key:
    secret-key: