server:
  port: 80
com:
  zsw:
    test:
      properties:
        merchants:
          a:
            name: zsw
            address: Earth

feign:
  # Hystrix支持，如果为true，hystrix库必须在classpath中
  # 使用 dashboard 必须开启此选项 EnableHystrix
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    max-connections-per-route: 50 # default
    max-connections: 200 # default
    # 连接超时，默认：2000/毫秒
    #    connection-timeout: 2000
    # 生存时间，默认：900L
    time-to-live: 900
    # 响应超时的时间单位，默认：TimeUnit.SECONDS
    timeToLiveUnit: SECONDS
  okhttp:
    # default true
    enabled: false
#  compression:
#    request:
#      #支持压缩的 mime types
#      enabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      ensbled: true
#\u5FAE\u670D\u52A1\u540D
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8
##    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: root
#    removeAbandoned: false
#    removeAbandonedTimeout: 1000
#    logAbandoned: false
#    driverClassName: com.mysql.jdbc.Driver
#    # \u4E0B\u9762\u4E3A\u8FDE\u63A5\u6C60\u7684\u8865\u5145\u8BBE\u7F6E\uFF0C\u5E94\u7528\u5230\u4E0A\u9762\u6240\u6709\u6570\u636E\u6E90\u4E2D
#    # \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
#    initialSize: 5
#    minIdle: 5
#    maxActive: 50
#    # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
#    maxWait: 60000
#    # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
#    timeBetweenEvictionRunsMillis: 60000
#    # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
#    filters: stat,wall,log4j
#    # \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    # \u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
#    useGlobalDataSourceStat: true
#    keepAlive: true
#    # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
#    druid:
#      # ------      \u8FDE\u63A5\u6C60\u914D\u7F6E      ------
#      initial-size: ${spring.datasource.initialSize}
#      max-active: ${spring.datasource.maxActive}
#      min-idle: ${spring.datasource.minIdle}
#      max-wait: ${spring.datasource.maxWait}
#      pool-prepared-statements: ${spring.datasource.poolPreparedStatements}
#      max-pool-prepared-statement-per-connection-size: ${spring.datasource.maxPoolPreparedStatementPerConnectionSize}
##      max-open-prepared-statements: # statement cache\u7684\u5927\u5C0F\uFF0C\u9ED8\u8BA4\u4E3A-1\uFF0C\u4E5F\u5C31\u662F\u4E0D\u9650\u5236
#      validation-query: ${spring.datasource.validationQuery}
##      validation-query-timeout:
#      test-on-borrow: ${spring.datasource.testOnBorrow}
#      test-on-return: ${spring.datasource.testOnReturn}
#      test-while-idle: ${spring.datasource.testWhileIdle}
#      time-between-eviction-runs-millis: ${spring.datasource.timeBetweenEvictionRunsMillis}
#      min-evictable-idle-time-millis: ${spring.datasource.minEvictableIdleTimeMillis}
##      max-evictable-idle-time-millis:
#      #\u914D\u7F6E\u591A\u4E2A\u82F1\u6587\u9017\u53F7\u5206\u9694
#      filters: ${spring.datasource.filters}
#      # ------      \u76D1\u63A7\u914D\u7F6E    ------
#      # WebStatFilter\u914D\u7F6E\uFF0C\u8BF4\u660E\u8BF7\u53C2\u8003Druid Wiki\uFF0C\u914D\u7F6E_\u914D\u7F6EWebStatFilter
##JPA Configuration:
#  impl:
#    database: MYSQL
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect
#    open-in-view: true
#  output:
#    ansi:
#      enabled: detect
eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
    disable-delta: true
  instance:
    hostname: localhost
    prefer-ip-address: true
