##服务器端口
server:
  port: 3337
  tomcat:
    port-header: PUT,DELETE,OPTIONS,GET,POST

##微服务名
spring:
  rabbitmq:
    username: guest
    password: guest
  application:
    name: mq
#    host: localhost
#    port: 5672

##服务发现地址
eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
  instance:
    hostname: localhost

zsw:
  base:
    mq:
      queue: spring-boot


info:
  version: @project.version@


