server:
  port: 80
spring:
  application:
    name: security-app
  security:
    user:
      name: root
      password: root
management:
  endpoints:
    web:
      exposure:
        include: "*"
    # 开启 micrometer 以 prometheus 输出，然后脱敏
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: true
    logfile:
      external-file: /data/spring/logs/${spring.application.name}
      enabled: true
