server:
  port: 80

# http://www.mybatis.org/mybatis-3/zh/configuration.html
#默认使用配置
mybatis:
  # 一些默认的 alias TypeAliasRegistry
  type-aliases-package: com.zsw.demo.persistence.entity,com.zsw.demo.mybatis.typehandler
  type-handlers-package: com.zsw.mybatis.typehandler
  mapper-locations: classpath:mapper/*.xml
  # 看这种配置方式，应该就能推断出静态调用参数设置的方式
  configuration:
    log-prefix: ${spring.application.name} # default 未设置
spring:
  application:
    name: docker-springboot
  datasource:
    url: jdbc:mysql://192.168.137.101:3306/spring?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
