server:
  port: 5555


spring:
  application:
    name: api-gateway


eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
  instance:
    hostname: localhost


zuul:
  routes:
    file-upload: /file/**
