server:
  port: 1301

spring:
  application:
    name: saleorder-controller
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
    disable-delta: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: localhost

com:
  zsw:
    servername:
      saleorder: saleorder-api

feign:
  httpclient:
    enabled: true
    max-connections-per-route: 50 # default
    max-connections: 200 # default
  okhttp:
    # default true
    enabled: false


security:
  oauth2:
    client:
      client-id: 2a1b448f53f7b4ee1bc5
      client-secret: 9ac0814f8f098395033d99031620c13d6279bad8
      access-token-uri: http://oauth2-server/oauth/token
#      user-authorization-uri: http://oauth2-server/oauth/authorize
#      pre-established-redirect-uri: http://localhost:1301/callback


