#服务器端口
server:
  port: 1110

##微服务名
spring:
  application:
    name: oauth2-server
#  devtools:
#    restart:
#      exclude: static/**,public/**,com
#  resources:
#    static-locations: classpath:/templates/
  # 支持 sso 登录
#  freemarker:
#    suffix: .html
#    request-context-attribute: request
#    expose-request-attributes: true
#    expose-session-attributes: true
#    expose-spring-macro-helpers: true
#  jackson:
#    serialization:
#      failOnEmptyBeans: false
#    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      #      max-lifetime: 30000
      idle-timeout: 600000
      connection-timeout: 30000
      register-mbeans: true
  #JPA Configuration:
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org:
      springframework:
        security: DEBUG

#management:
#  security:
#    enabled: false

com:
  zsw:
    oauth2:
      key-store-file: /data/keystore/oauth2.jks
      key-store-pwd: 111111
      key-pair: oauth2


#/oauth/authorize：验证接口， AuthorizationEndpoint
#/oauth/token：获取token
#/oauth/confirm_access：用户授权
#/oauth/error：认证失败
#/oauth/check_token：资源服务器用来校验token
#/oauth/token_key：jwt模式下获取公钥；位于：TokenKeyEndpoint ，通过 JwtAccessTokenConverter 访问key

info:
  version: @project.version@
