server:
  port: 8080
spring:
  redis:
    host: 192.168.1.12
    port: 6379
    database: 0
    password: Anf34l_Fs
    lettuce:
      pool:
        max-idle: 2
        max-active: 8
  application:
    name: api-tests