spring:
  application:
    name: simple-api
  task:
    scheduling:
      pool:
        size: 2
      thread-name-prefix: test-scheduling-
server:
  port: 8081
jobs:
  work: 5000

#eureka:
#  server:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone:  http://${eureka.server.hostname}:${eureka.client.eureka-server-port}/eureka/
#    eureka-server-port: 18080
#  instance:
##    hostname: 127.0.0.1
#    prefer-ip-address: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    prometheus:
#      enabled: true
#    health:
#      enabled: true
#      show-details: ALWAYS
#    shutdown:
#      enabled: true
#    logfile:
#      enabled: true
