security:
  oauth2:
    client:
      client-id: 2a1b448f53f7b4ee1bc5
      client-secret: 9ac0814f8f098395033d99031620c13d6279bad8
      access-token-uri: http://${com.zsw.server.oauth2}/oauth/token
      # 不能缺 必须是 client_credentials, 默认 authorization_code 是跳转登录方式
      grant-type: client_credentials
      user-authorization-uri: http://${com.zsw.server.oauth2}/oauth/authorize
#      pre-established-redirect-uri: http://localhost:1301/callback


com:
  zsw:
    server:
      oauth2: oauth2-server