##服务器端口
server:
  port: 3335
  tomcat:
    port-header: PUT,DELETE,OPTIONS,GET,POST

##微服务名
spring:
  application:
    name: ui-server
  output:
    ansi:
      enabled: detect

##服务发现地址
eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
  instance:
    hostname: localhost

feign:
  hystrix:
    enabled: true

com:
  zsw:
    servername:
      saleorder: api-server

logging:
  level: debug

management:
  security:
    enabled: false

info:
  version: @project.version@




