spring:
  application:
    name: ui-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 3335

eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 1111
    disable-delta: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: localhost

com:
  zsw:
    servername:
      saleorder: core-server

feign:
  httpclient:
    enabled: true
    max-connections-per-route: 50 # default
    max-connections: 200 # default
    time-ti-live: 900L
  okhttp:
    # default true
    enabled: false
logging:
  level:
    org:
      springframework:
        cloud:
          netflix: DEBUG
#logging:
#  level:
#    com:
#      netflix:
#        hystrix: DEBUG


